### ISSUE TITLE
 15 Books by Black Scholars the Tech Industry Needs to Read Now

### ISSUE THREAD

**Issue by tatecarson** [shiffman/anti-racism-reading-list#5]
I just found this list. I'm not sure how to handle adding books from other lists and giving credit to the original curators. 

[15 Books by Black Scholars the Tech Industry Needs to Read Now](https://www.c2i2.ucla.edu/racial-justice-and-tech/)

**Comment by shiffman** [comment]
What if at the top of the README there could be a list of links to other lists?

**Comment by tatecarson** [comment]
I was also thinking we could add them to the list but use a citation system. Some of the books on that list while very important are not about tech. I think it's great to have more narrow resources like this one to give out to people who are involved in tech. Maybe both? I'm torn between conciseness and inclusion. A lot of the awesome lists that are disorganied are overwhelming and difficult to use. Thoughts?

**Comment by shiffman** [comment]
The reason I started this list was to specifically have a reference for my coding and machine learning courses. So I might focus on that and link out to other lists in a secondary document or under a different category?
